OSINT tool for termux
How to run

git clone https://github.com/prokiller0808/Prokiller.git
..........................................................
chmod +x osint_tool.py
.........................................
pkg install python python-pip nmap traceroute
.................................................
pip install requests dnspython python-whois
.................................................
Run: 

........................................................
./osint_tool.py <target> [options]
..............................................................

Example Usage:
....................................................
./osint_tool.py google.com -w -d -n -t -g          (Performs all lookups)
.................................................................................
./osint_tool.py 8.8.8.8 -g                  (Gets geolocation information)
........................................................................................
./osint_tool.py google.com -n 80,443        (Nmap scan on ports 80 and 443)
